### ISSUE TITLE
Map changes after a capture the flag win or one player gets > 20(?) kills in FFA

### ISSUE THREAD

**Issue by mes258** [vinport16/KHE19#10]
In capture the flag I think the teams should stay the same people just respawn on a new map at the end of the game. 

In free for all, after a player gets n kills, the everyone respawns on a new map. I don't think the leaderboard should reset.

**Comment by vinport16** [comment]
this should be set in the config file

**Comment by vinport16** [comment]
- [ ] specify map set in config file
- [ ] have code on the client to delete the map object + replace it with a new map
- [ ] have code on the server that manages when to reset the map (on game end)

**Comment by mes258** [comment]
Map doesn't change on reset but the reset works and can be turned on or off in the config file.
